### ISSUE TITLE
Generator always fails to create brew-cask

### ISSUE THREAD

**Issue by 0xErnie** [seethroughdev/homebrew-dotfile-generator#11]
OS-X 10.13.2
node v9.4.0
Homebrew 1.5.3
Homebrew-Cask 1.5.3

After installing the generator following the README.md the generator always fails to create the brew-cask file.

```
$ node app -p $(mktemp -d)
.brew was written to /var/folders/2t/40gkqtyx2vvcnx5vd4x9_m5r0000gn/T/tmp.KYD8ggnU
brew-cask already exists!  Change path or add -f to force.
Brewfile was written to /var/folders/2t/40gkqtyx2vvcnx5vd4x9_m5r0000gn/T/tmp.KYD8ggnU
```

**Comment by seethroughtrees** [comment]
Hi @0xErnie , sorry for the delay.  

Homebrew deprecated this feature:  https://github.com/Homebrew/legacy-homebrew/issues/32952, so this repo was deprecated along with it.  

I'll update the readme.

**Comment by seethroughdev** [comment]
Looks like this might help too:  https://github.com/Homebrew/homebrew-bundle
